var barang;
barang=prompt("Masukkan Nama Barang :","");
var harga;
harga=prompt("Masukkan Harga Barang :","");
var beli; 
beli=prompt("Masukkan Jumlah Beli :","");
var total = harga*beli;
var nama;
nama=prompt("Masukkan Nama Anda :","");
document.write("<table border='1'>");
document.write("<tr><th>Nama Barang</th>");
document.write("<th>Harga Barang</th>");
document.write("<th>Jumlah Beli</th>");
document.write("<th>Sub Total</th>");
document.write("</tr>");
document.write("<tr><td>"+barang+"</td>");
document.write("<td>"+harga+"</td>");
document.write("<td>"+beli+"</td>");
document.write("<td>"+total+"</td></tr>");
document.write("<tr><td colspan='4'>"+nama+"</td></tr>");
document.write("</table>");